// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: com/pistonint/grpc/query/mongo/bucket_resp.proto

package mongo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分区统计返回
type BucketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 统计字段
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// 总计
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// 所有桶数量
	Buckets int32 `protobuf:"varint,3,opt,name=buckets,proto3" json:"buckets,omitempty"`
	// 各个值统计结果
	Contents []*BucketResp_Item `protobuf:"bytes,4,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *BucketResp) Reset() {
	*x = BucketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResp) ProtoMessage() {}

func (x *BucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResp.ProtoReflect.Descriptor instead.
func (*BucketResp) Descriptor() ([]byte, []int) {
	return file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescGZIP(), []int{0}
}

func (x *BucketResp) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BucketResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BucketResp) GetBuckets() int32 {
	if x != nil {
		return x.Buckets
	}
	return 0
}

func (x *BucketResp) GetContents() []*BucketResp_Item {
	if x != nil {
		return x.Contents
	}
	return nil
}

type BucketResp_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// title
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// value
	Value int32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BucketResp_Item) Reset() {
	*x = BucketResp_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResp_Item) ProtoMessage() {}

func (x *BucketResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResp_Item.ProtoReflect.Descriptor instead.
func (*BucketResp_Item) Descriptor() ([]byte, []int) {
	return file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BucketResp_Item) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BucketResp_Item) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_com_pistonint_grpc_query_mongo_bucket_resp_proto protoreflect.FileDescriptor

var file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDesc = []byte{
	0x0a, 0x30, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f,
	0x2f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e,
	0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e,
	0x67, 0x6f, 0x22, 0xd3, 0x01, 0x0a, 0x0a, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x4b, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x1a, 0x32, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x50, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x42, 0x0f, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1b, 0x70,
	0x69, 0x73, 0x74, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescOnce sync.Once
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescData = file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDesc
)

func file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescGZIP() []byte {
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescOnce.Do(func() {
		file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescData)
	})
	return file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDescData
}

var file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_pistonint_grpc_query_mongo_bucket_resp_proto_goTypes = []interface{}{
	(*BucketResp)(nil),      // 0: com.pistonint.grpc.query.mongo.BucketResp
	(*BucketResp_Item)(nil), // 1: com.pistonint.grpc.query.mongo.BucketResp.Item
}
var file_com_pistonint_grpc_query_mongo_bucket_resp_proto_depIdxs = []int32{
	1, // 0: com.pistonint.grpc.query.mongo.BucketResp.contents:type_name -> com.pistonint.grpc.query.mongo.BucketResp.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_com_pistonint_grpc_query_mongo_bucket_resp_proto_init() }
func file_com_pistonint_grpc_query_mongo_bucket_resp_proto_init() {
	if File_com_pistonint_grpc_query_mongo_bucket_resp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketResp_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_pistonint_grpc_query_mongo_bucket_resp_proto_goTypes,
		DependencyIndexes: file_com_pistonint_grpc_query_mongo_bucket_resp_proto_depIdxs,
		MessageInfos:      file_com_pistonint_grpc_query_mongo_bucket_resp_proto_msgTypes,
	}.Build()
	File_com_pistonint_grpc_query_mongo_bucket_resp_proto = out.File
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_rawDesc = nil
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_goTypes = nil
	file_com_pistonint_grpc_query_mongo_bucket_resp_proto_depIdxs = nil
}
