// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: com/pistonint/grpc/query/mongo/mongo_id.proto

package mongo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// id 类型
type MongoIdType int32

const (
	// 整型
	MongoIdType_INTEGER MongoIdType = 0
	// 长整型
	MongoIdType_LONG MongoIdType = 1
	// 字符串
	MongoIdType_STRING MongoIdType = 2
	// ObjectId
	MongoIdType_OBJECT_ID MongoIdType = 3
)

// Enum value maps for MongoIdType.
var (
	MongoIdType_name = map[int32]string{
		0: "INTEGER",
		1: "LONG",
		2: "STRING",
		3: "OBJECT_ID",
	}
	MongoIdType_value = map[string]int32{
		"INTEGER":   0,
		"LONG":      1,
		"STRING":    2,
		"OBJECT_ID": 3,
	}
)

func (x MongoIdType) Enum() *MongoIdType {
	p := new(MongoIdType)
	*p = x
	return p
}

func (x MongoIdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MongoIdType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_pistonint_grpc_query_mongo_mongo_id_proto_enumTypes[0].Descriptor()
}

func (MongoIdType) Type() protoreflect.EnumType {
	return &file_com_pistonint_grpc_query_mongo_mongo_id_proto_enumTypes[0]
}

func (x MongoIdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MongoIdType.Descriptor instead.
func (MongoIdType) EnumDescriptor() ([]byte, []int) {
	return file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescGZIP(), []int{0}
}

// id 实体
type MongoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 主键类型
	Type MongoIdType `protobuf:"varint,1,opt,name=type,proto3,enum=com.pistonint.grpc.query.mongo.MongoIdType" json:"type,omitempty"`
	// 主键值
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MongoId) Reset() {
	*x = MongoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MongoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoId) ProtoMessage() {}

func (x *MongoId) ProtoReflect() protoreflect.Message {
	mi := &file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoId.ProtoReflect.Descriptor instead.
func (*MongoId) Descriptor() ([]byte, []int) {
	return file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescGZIP(), []int{0}
}

func (x *MongoId) GetType() MongoIdType {
	if x != nil {
		return x.Type
	}
	return MongoIdType_INTEGER
}

func (x *MongoId) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// id 列表
type MongoIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 主键类型
	Ids []*MongoId `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MongoIds) Reset() {
	*x = MongoIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MongoIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoIds) ProtoMessage() {}

func (x *MongoIds) ProtoReflect() protoreflect.Message {
	mi := &file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoIds.ProtoReflect.Descriptor instead.
func (*MongoIds) Descriptor() ([]byte, []int) {
	return file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescGZIP(), []int{1}
}

func (x *MongoIds) GetIds() []*MongoId {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_com_pistonint_grpc_query_mongo_mongo_id_proto protoreflect.FileDescriptor

var file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f,
	0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x22,
	0x60, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x2e, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x49,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x45, 0x0a, 0x08, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x49, 0x64, 0x73, 0x12, 0x39, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x2e, 0x4d, 0x6f, 0x6e, 0x67,
	0x6f, 0x49, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73, 0x2a, 0x3f, 0x0a, 0x0b, 0x4d, 0x6f, 0x6e, 0x67,
	0x6f, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47,
	0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x42,
	0x4a, 0x45, 0x43, 0x54, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x42, 0x4d, 0x0a, 0x1e, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x69, 0x73, 0x74, 0x6f, 0x6e, 0x69, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x42, 0x0c, 0x4d, 0x6f, 0x6e,
	0x67, 0x6f, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1b, 0x70, 0x69, 0x73,
	0x74, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescOnce sync.Once
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescData = file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDesc
)

func file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescGZIP() []byte {
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescOnce.Do(func() {
		file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescData)
	})
	return file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDescData
}

var file_com_pistonint_grpc_query_mongo_mongo_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_pistonint_grpc_query_mongo_mongo_id_proto_goTypes = []interface{}{
	(MongoIdType)(0), // 0: com.pistonint.grpc.query.mongo.MongoIdType
	(*MongoId)(nil),  // 1: com.pistonint.grpc.query.mongo.MongoId
	(*MongoIds)(nil), // 2: com.pistonint.grpc.query.mongo.MongoIds
}
var file_com_pistonint_grpc_query_mongo_mongo_id_proto_depIdxs = []int32{
	0, // 0: com.pistonint.grpc.query.mongo.MongoId.type:type_name -> com.pistonint.grpc.query.mongo.MongoIdType
	1, // 1: com.pistonint.grpc.query.mongo.MongoIds.ids:type_name -> com.pistonint.grpc.query.mongo.MongoId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_com_pistonint_grpc_query_mongo_mongo_id_proto_init() }
func file_com_pistonint_grpc_query_mongo_mongo_id_proto_init() {
	if File_com_pistonint_grpc_query_mongo_mongo_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MongoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MongoIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_pistonint_grpc_query_mongo_mongo_id_proto_goTypes,
		DependencyIndexes: file_com_pistonint_grpc_query_mongo_mongo_id_proto_depIdxs,
		EnumInfos:         file_com_pistonint_grpc_query_mongo_mongo_id_proto_enumTypes,
		MessageInfos:      file_com_pistonint_grpc_query_mongo_mongo_id_proto_msgTypes,
	}.Build()
	File_com_pistonint_grpc_query_mongo_mongo_id_proto = out.File
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_rawDesc = nil
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_goTypes = nil
	file_com_pistonint_grpc_query_mongo_mongo_id_proto_depIdxs = nil
}
